name: bonfire
description: "A modern take on the Discord Client"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  nyxx:
    git:
      url: https://github.com/Bonfire-Development/firebridge
      ref: dev

  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  discord_api: ^0.1.1
  webview_flutter: ^4.7.0
  flutter_webview_plugin: ^0.4.0
  url_launcher: ^6.2.6
  flutter_inappwebview: ^6.0.0
  flutter_riverpod: ^2.5.1
  flutter_js: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  custom_lint:
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true