name: guildcable
description: "A modern take on the Discord Client"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0-5.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  riverpod: ^2.5.1
  google_fonts: ^6.2.1
  discord_api: ^0.1.1
  flutter_webview_plugin: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
