name: Flutter Build

on: [push, pull_request]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.22.2

      - name: Install dependencies
        run: flutter pub get

      # - name: Run tests
      #   run: flutter test

      - name: Build Android APK
        run: flutter build apk

      - name: Build Android App Bundle
        run: flutter build appbundle

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      # Ensure Java 17 is also set up for Windows if needed
      - name: Set up Java 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      # - name: Run tests
      #   run: flutter test

      - name: Build Windows
        run: flutter build windows

  # Add similar steps for Linux and macOS if they require Java 17
  # You can also specify a global Java setup step if all environments need Java 17

